In [1]:
#To get the average frame count 
import json
import glob
import numpy as np
import cv2
import copy

video_files =  glob.glob('../Dataset/YouTube-Real/*.mp4')
# video_files =  glob.glob('../Dataset/Celeb-real/*.mp4')
frame_count = []
for video_file in video_files:
  cap = cv2.VideoCapture(video_file)
  if(int(cap.get(cv2.CAP_PROP_FRAME_COUNT))<150):
    video_files.remove(video_file)
    continue
  frame_count.append(int(cap.get(cv2.CAP_PROP_FRAME_COUNT)))
print("frames" , frame_count)
print("Total number of videos: " , len(frame_count))
print('Average frame per video:',np.mean(frame_count))

frames [450, 415, 512, 295, 450, 463, 486, 474, 477, 575, 422, 470, 397, 474, 461, 442, 319, 282, 435, 468, 456, 462, 471, 463, 547, 470, 499, 481, 473, 463, 472, 510, 463, 461, 505, 458, 550, 455, 467, 459, 381, 456, 383, 472, 464, 459, 471, 489, 484, 476, 470, 367, 464, 468, 417, 468, 534, 466, 507, 474, 478, 412, 478, 477, 429, 493, 457, 474, 476, 432, 357, 508, 478, 475, 471, 474, 479, 475, 492, 386, 478, 452, 462, 359, 408, 658, 482, 468, 493, 485, 416, 455, 549, 495, 414, 487, 305, 502, 453, 494, 534, 440, 457, 474, 499, 504, 327, 462, 478, 264, 479, 467, 477, 504, 340, 312, 471, 462, 474, 424, 468, 468, 362, 303, 421, 280, 455, 483, 460, 467, 398, 357, 350, 499, 481, 354, 293, 353, 481, 553, 382, 445, 450, 462, 451, 469, 722, 514, 459, 506, 461, 504, 698, 488, 375, 573, 445, 450, 455, 448, 490, 519, 447, 475, 526, 470, 469, 477, 476, 432, 348, 436, 353, 499, 465, 483, 605, 521, 468, 451, 349, 391, 478, 516, 467, 474, 510, 460, 476, 410, 465, 442, 474, 353, 462, 495, 480, 467, 45

In [2]:
# !pip3 install face_recognition
#!mkdir Face_Crop
import torch
import torchvision
from torchvision import transforms
from torch.utils.data import DataLoader
from torch.utils.data.dataset import Dataset
import os
import numpy as np
import cv2
import matplotlib.pyplot as plt
import face_recognition
from tqdm.notebook import tqdm
from facenet_pytorch import MTCNN

device = torch.device("cuda" if torch.cuda.is_available() else "cpu") #USE CUDA if gpu is represent

In [5]:

# to extract frame
def frame_extract(path):
  vidObj = cv2.VideoCapture(path) 
  success = 1
  cnt=0

  while success and cnt<=150: #Extract only first 150 frames from video with cropped to face     
      success, image = vidObj.read()
      if success:
          #filename = str(cnt) + '.jpg'   
          #cv2.imwrite(filename,image)
          cnt+=1
          yield image
          

# process the frames
def create_face_videos(path_list,out_dir):
  already_present_count =  glob.glob(out_dir+'*.mp4')
  print("No of videos already present " , len(already_present_count))

  
  for path in tqdm(path_list):   
    #print(path)
    out_path = os.path.join(out_dir,"yt_"+path.split('\\')[-1])
    print(out_path)
    file_exists = glob.glob(out_path)
    if(len(file_exists) != 0):
      print("File Already exists: " , out_path)
      continue
    frames = []
    flag = 0
    face_all = []
    frames1 = []
    out = cv2.VideoWriter(out_path,cv2.VideoWriter_fourcc('M','J','P','G'), 30, (112,112))
    face_detector = MTCNN(device=device) #MTCNN for face detection
    for idx,frame in enumerate(frame_extract(path)):
        try:
            face = face_detector.detect(frame)[0][0]
        except:
            continue
        print(face)
        try:
            #filename = str(idx) + '.jpg'
            left,bottom,right,top=face
            left=int(left)
            bottom=int(bottom)
            right=int(right)
            top=int(top)
            img=cv2.resize(frame[bottom:top,left:right],(112,112))
            #isWrite=cv2.imwrite(filename,img)
            # print(isWrite)  
            out.write(img)
        except:
            pass
        
      
    try:
      del top,right,bottom,left
    except:
      pass
    out.release()

In [ ]:
create_face_videos(video_files,'./Face_Crop\\')

No of videos already present  3148


  0%|          | 0/299 [00:00<?, ?it/s]

./Face_Crop\yt_00000.mp4
[319.6518859863281 137.7266387939453 406.0129699707031 252.30740356445312]
[320.326904296875 138.69541931152344 405.16644287109375 250.91920471191406]
[320.6293029785156 138.58177185058594 405.65509033203125
 251.15257263183594]
[319.6778564453125 138.4010467529297 405.28558349609375 250.5304718017578]
[320.12774658203125 139.41050720214844 405.4317321777344 252.578857421875]
[320.8433837890625 139.08595275878906 405.9278259277344 250.1305389404297]
[321.472412109375 140.4873504638672 405.1246032714844 247.3143768310547]
[320.72698974609375 139.99615478515625 405.2777099609375
 248.59095764160156]
[321.7916259765625 138.18695068359375 406.7241516113281 247.1229248046875]
[321.11083984375 138.8668670654297 405.1370544433594 245.04823303222656]
[322.1473388671875 138.79959106445312 405.58209228515625 243.5228729248047]
[323.1595153808594 137.46878051757812 406.18341064453125
 242.62989807128906]
[323.39239501953125 136.54360961914062 406.7052917480469 241.9568634